language: php

matrix:
  fast_finish: true

  include:
    - php: 5.5
      env: TYPO3_BRANCH="TYPO3_6-2"
    - php: 5.5
      env: TYPO3_BRANCH="master"
    - php: 5.6
      env: TYPO3_BRANCH="TYPO3_6-2"
    - php: 5.6
      env: TYPO3_BRANCH="master"
    - php: 7
      env: TYPO3_BRANCH="master"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer self-update
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv typo3-extension-cacheopt typo3conf/ext/cacheopt

script:
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find . -wholename '*typo3conf/ext/cacheopt/Tests/Functional/*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; ./bin/phpunit --colors -c typo3/sysext/core/Build/FunctionalTests.xml {}'