language: php
sudo: false

matrix:
  include:
    - php: 5.6
      env: TYPO3_VERSION=^6.2
    - php: 7
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - mysql -e 'CREATE DATABASE typo3;'

before_script:
  # First we install all required packages as dist versions.
  - composer require typo3/cms=$TYPO3_VERSION --prefer-dist
  - export TYPO3_PATH_WEB="$PWD/.Build/Web"
  - mkdir -p $TYPO3_PATH_WEB/typo3conf/ext
  - ln -s $PWD $TYPO3_PATH_WEB/typo3conf/ext/cacheopt

script:
  - >
    echo;
    echo "Running phpcs";
    .Build/bin/phpcs --config-set installed_paths "Tests/CodeSniffer,`pwd`/.Build/vendor/de-swebhosting/php-codestyle/PhpCodeSniffer";
    .Build/bin/phpcs --standard=PSRCacheopt Classes Tests/Functional ext_localconf.php;
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="127.0.0.1";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    ./.Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional
